### ISSUE TITLE
Overview of Recent Bugs, Tweaks & Updates for 1.0.0

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkerData#27]
- [x] #24 
- [x] [Overlays not working](https://github.com/TheAcharya/MarkerData/issues/18#issuecomment-1837203317)
- [x] [Remove `Clip Boundaries` and `Exclude Roles` options](https://github.com/TheAcharya/MarkerData/issues/14#issuecomment-1858996671)
- [x] [Adding`Marker Source` Option](https://github.com/TheAcharya/MarkerData/issues/13#issuecomment-1837693427)
- [x] [Updating Log file name and Location](https://github.com/TheAcharya/MarkerData/issues/6#issuecomment-1837196390)
- [x] #26
- [x] [Switch to `JSON` for Notion and updating Notion Panel and backend code](https://github.com/TheAcharya/MarkerData/issues/4#issuecomment-1865356991)
- [x] [Updating Airtable Panel](https://github.com/TheAcharya/MarkerData/issues/2#issuecomment-1862100313)
- [x] [Remove Database App Menu](https://github.com/TheAcharya/MarkerData/issues/16#issuecomment-1837301058)
- [x] #29 
- [x] [Improve Destination Folder Picker Behaviour and Logic](https://github.com/TheAcharya/MarkerData/issues/14#issuecomment-1877810314)
- [x] [Tweak Folder Picker Font](https://github.com/TheAcharya/MarkerData/issues/14#issuecomment-1879295995)
- [x]  [Remove Trash Icon but have a way to clear the folder](https://github.com/TheAcharya/MarkerData/issues/14#issuecomment-1879312105)
- [x]  [Change default stroke colour to black](https://github.com/TheAcharya/MarkerData/issues/18#issuecomment-1879482608)
- [x] [Tweak "Changed" text badge colour](https://github.com/TheAcharya/MarkerData/issues/15#issuecomment-1879491829)
- [x]  [Improve Image Size Logic](https://github.com/TheAcharya/MarkerData/issues/13#issuecomment-1879498050)
- [x]  [Fix Text Truncation](https://github.com/TheAcharya/MarkerData/issues/13#issuecomment-1879498050)
- [x] [Tweak Alignment](https://github.com/TheAcharya/MarkerData/issues/18#issuecomment-1879505299)
- [x]  [Add "Command + s" shortcut  ](https://github.com/TheAcharya/MarkerData/issues/15#issuecomment-1879921237)
- [x]  [Tweak Image Size header names](https://github.com/TheAcharya/MarkerData/issues/13#issuecomment-1880168671)
- [x] #32
- [x] #33 
- [x]  [Remove AirtableKit from dependencies](https://github.com/TheAcharya/MarkerData/issues/2#issuecomment-1890467002)
- [x]  [Add Notion Workspace Field](https://github.com/TheAcharya/MarkerData/issues/4#issuecomment-1891189418)
- [x] [On fresh Install of Maker Data, "Changed" text badge appears](https://github.com/TheAcharya/MarkerData/issues/15#issuecomment-1894874317)
- [x] [Under Image Setting, in default mode, when selecting GIF, the size is still at 100%](https://github.com/TheAcharya/MarkerData/issues/13#issuecomment-1894880314)
- [x] [Share Destination Tweaks and Bugs](https://github.com/TheAcharya/MarkerData/issues/1#issuecomment-1897590062)
- [x] [Tweak Colour Picker Position](https://github.com/TheAcharya/MarkerData/issues/18#issuecomment-1899611523)
- [x] #36
- [x] [Tweak Extract Profile's Dropdown menu width](https://github.com/TheAcharya/MarkerData/issues/14#issuecomment-1902646825)
- [x] [Move Notification Settings to General Panel ](https://github.com/TheAcharya/MarkerData/issues/8#issuecomment-1902642224)
- [x] [Add Check box toggle for Dock Icon Progress Bar](https://github.com/TheAcharya/MarkerData/issues/28#issuecomment-1902879010)
- [x] [Add confirmation dialogue box](https://github.com/TheAcharya/MarkerData/issues/15#issuecomment-1903865278)
- [x] [Tweak FCPExport to .fcpexport](https://github.com/TheAcharya/MarkerData/issues/1)
- [x] #3
- [x] [Add confirmation dialogue box for deleting Database Profile](https://github.com/TheAcharya/MarkerData/issues/16#issuecomment-1913607587)
- [x] #41 
- [x] #40 
- [x] [On fresh Install of Maker Data, "Changed" text badge appears](https://github.com/TheAcharya/MarkerData/issues/15#issuecomment-1913820220)
- [x] [Roles exclusion logic is not working correctly](https://github.com/TheAcharya/MarkerData/issues/21#issuecomment-1913854011)
- [x]  [Add `Show Caches` and `Clean Caches` items under, File menu](https://github.com/TheAcharya/MarkerData/issues/1#issuecomment-1913855868)
- [x] [Rename Exported Log Files and rename `Debug` to `Debug Console`](https://github.com/TheAcharya/MarkerData/issues/6#issuecomment-1913867313)
- [x]  [Notification Bug](https://github.com/TheAcharya/MarkerData/issues/8#issuecomment-1915937368)
- [x] #43 
- [x] [Drag & Drop not working in Roles's Tab](https://github.com/TheAcharya/MarkerData/issues/21#issuecomment-1916748269)
- [x] #44 
- [x] #45 
- [x] [Minor UI Tweaks for Configuration Panel](https://github.com/TheAcharya/MarkerData/issues/15#issuecomment-1918481346)
- [x] #46 
- [x] [Adding `Merge Only` to Notion Module](https://github.com/TheAcharya/MarkerData/issues/4#issuecomment-1922769170)
- [x] [Add File and Disk Access Links under General, File Tab](https://github.com/TheAcharya/MarkerData/issues/19#issuecomment-1925537624)
- [x] [Adding `⌘ + z` for `Discard Changes](https://github.com/TheAcharya/MarkerData/issues/47#issuecomment-1926008094)
- [x] Remove `Debug Console` from Help Menu
- [x] [Tweak Dropbox Configured status behaviour](https://github.com/TheAcharya/MarkerData/issues/2#issuecomment-1938115941) 
- [x] [Discard Changes Bug](https://github.com/TheAcharya/MarkerData/issues/47#issuecomment-1939916649)
- [x] [Add Dropbox link](https://github.com/TheAcharya/MarkerData/issues/2#issuecomment-1940043043)
- [x] [Airtable's Rename Key Column is not working](https://github.com/TheAcharya/MarkerData/issues/2#issuecomment-1940411401)
- [x] #52
- [x] [Tweak Workflow Extension Icon & Text Position](https://github.com/TheAcharya/MarkerData/issues/3#issuecomment-1943053203)
- [x] [Add `--verbose` for Notion](https://github.com/TheAcharya/MarkerData/issues/4#issuecomment-1937988986)
- [x] #55 
- [x] [Improve Queue Panel Logic & Behaviour](https://github.com/TheAcharya/MarkerData/issues/22#issuecomment-1947646940)
- [x] [Add `--verbose` for Airtable & Auto Close Terminal](https://github.com/TheAcharya/MarkerData/issues/2#issuecomment-1947678006)
- [x] #56 
- [x] [Remember the column width adjustments for Queue Panel](https://github.com/TheAcharya/MarkerData/issues/22#issuecomment-1950726371)
- [x] [Tweak Clear behaviour and logic](https://github.com/TheAcharya/MarkerData/issues/22#issuecomment-1953304624)
- [x] #57 
- [x] [Tweak code for reading Caption Roles](https://github.com/TheAcharya/MarkerData/issues/21#issuecomment-1953689555)
- [x] #58 
- [x] Change App Version numbering to 3 digit `1.0.0`
- [x] Auto update and append `appcast.xml` via GitHub Action
- [x] #62 
- [x] [Tweak Queue Column & Fix and Improve logic Automatic Scan of `Load from Export Destination` ](https://github.com/TheAcharya/MarkerData/issues/22#issuecomment-1963153638)
- [x] [Add Tooltip for Name Mouse Over](https://github.com/TheAcharya/MarkerData/issues/22#issuecomment-1965636575)
- [x] [Can't able to type 2 digits in Image Size](https://github.com/TheAcharya/MarkerData/issues/13#issuecomment-1965668281)
- [x] #5
- [x] #63 
- [x] #17 
- [x] [Update `Palette Filename` column Bug](https://github.com/TheAcharya/MarkerData/issues/17#issuecomment-2068283218)
- [x] [Revert Colour Swatch behaviour](https://github.com/TheAcharya/MarkerData/issues/17#issuecomment-2069268781)
- [x] #65 
- [x] #66 
- [x] #67 
- [x] [Roles extraction bug](https://github.com/TheAcharya/MarkerData/issues/21#issuecomment-2073784525)
- [x] #68
- [x] [`Enable Swatch` grey out when users select CSV/TSV with GIF](https://github.com/TheAcharya/MarkerData/issues/17#issuecomment-2075961286)
- [x] #69
- [x] #73 
- [x] #76 
- [x] #77 
- [x] #78 
- [x] #71 
- [x] #72 
- [x] [Add `Accuracy` option after `Algorithm` under Swatch Tab](https://github.com/TheAcharya/MarkerData/issues/72#issuecomment-2091495507)
- [x] [Use `darkness` as the sorting](https://github.com/TheAcharya/MarkerData/issues/72#issuecomment-2091495507)
- [x] [Tweak `progress bar` to include `Analysing Swatch` if Swatch is enabled](https://github.com/TheAcharya/MarkerData/issues/72#issuecomment-2091703802)
- [x] #81 
- [x] #82 
- [x] #83 
- [x] [DominantColors fix for `CIE94` and `CIEDE2000` ](https://github.com/TheAcharya/MarkerData/issues/72#issuecomment-2099925884)
- [x] #85
- [x] #87
- [x] #88 
- [x] #89
- [x] #90
- [x] #91
- [x] #92
- [x] #93
- [x] #94
- [x] #95 
- [x] #96 
- [x] #98 
- [x] #99 
- [x] #101 
- [x] #103
